@extends('layouts.app')
@section('content')
<style>
  .portfolio-home{width:100%}.portfolio-hero{width:calc(100% + (2 * clamp(20px,4vw,56px)));margin-left:calc(-1 * clamp(20px,4vw,56px));min-height:clamp(450px,64vh,650px);display:grid;grid-template-columns:minmax(0,1.15fr) minmax(300px,.85fr);gap:32px;align-items:end;padding:clamp(30px,5vw,72px);border-radius:0 0 30px 30px;color:#fff;position:relative;overflow:hidden;background:linear-gradient(118deg,#173da8,#2563eb 45%,#6366f1);box-shadow:0 28px 72px rgba(37,99,235,.23),inset 0 1px 0 rgba(255,255,255,.32)}
  .portfolio-hero:before{content:'';position:absolute;width:480px;height:480px;right:-80px;top:-180px;border-radius:50%;background:rgba(255,255,255,.12)}.portfolio-hero:after{content:'';position:absolute;width:260px;height:260px;left:42%;bottom:-180px;border-radius:50%;background:rgba(111,91,255,.4);filter:blur(12px)}.portfolio-hero>*{position:relative;z-index:1}.portfolio-kicker{display:inline-flex;align-items:center;gap:8px;margin-bottom:18px;font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;opacity:.84}.portfolio-hero h1{color:#fff;font-size:clamp(42px,7vw,92px);line-height:.94;letter-spacing:-.075em;max-width:800px;margin-bottom:22px}.portfolio-hero-copy{max-width:580px;color:rgba(255,255,255,.8);font-size:16px;line-height:1.7}.portfolio-hero-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:28px}.portfolio-hero-actions .btn{box-shadow:0 10px 22px rgba(15,45,130,.18)}.portfolio-hero-actions .btn-outline{color:#fff;border-color:rgba(255,255,255,.4);background:rgba(255,255,255,.13)}
  .hero-showcase{align-self:stretch;display:flex;align-items:flex-end;justify-content:flex-end}.showcase-panel{width:min(100%,350px);padding:24px;border:1px solid rgba(255,255,255,.3);border-radius:24px;background:rgba(255,255,255,.14);box-shadow:inset 0 1px 0 rgba(255,255,255,.28);backdrop-filter:blur(18px)}.showcase-panel-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:26px;font-size:12px;color:rgba(255,255,255,.7)}.showcase-live{display:inline-flex;align-items:center;gap:6px;color:#d6ffe3}.showcase-live:before{content:'';width:7px;height:7px;border-radius:50%;background:#7df0a5;box-shadow:0 0 0 4px rgba(125,240,165,.17)}.showcase-number{font-size:46px;font-weight:800;line-height:1;letter-spacing:-.06em}.showcase-label{margin-top:8px;color:rgba(255,255,255,.68);font-size:13px}.showcase-rule{height:1px;margin:22px 0;background:rgba(255,255,255,.2)}.showcase-row{display:flex;justify-content:space-between;gap:14px;font-size:13px}.showcase-row span:first-child{color:rgba(255,255,255,.65)}
  .portfolio-section{margin-top:34px}.portfolio-section-heading{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:16px}.portfolio-section-heading p{color:var(--muted);font-size:13px}.portfolio-section-heading .section-title{font-size:26px}.metric-strip{display:grid;grid-template-columns:repeat(3,1fr);overflow:hidden;border-radius:20px;background:rgba(255,255,255,.62);border:1px solid rgba(255,255,255,.9);box-shadow:0 14px 32px rgba(45,78,145,.07)}.metric-item{display:flex;align-items:center;gap:13px;padding:20px 24px;border-right:1px solid rgba(148,163,184,.18)}.metric-item:last-child{border-right:0}.metric-item i{display:grid;place-items:center;width:38px;height:38px;border-radius:13px;color:#2563eb;background:#eaf2ff;font-size:18px}.metric-value{color:var(--dark);font-weight:800;font-size:20px;line-height:1.1}.metric-label{color:var(--muted);font-size:12px;margin-top:3px}
  .service-row{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.service-item{display:flex;align-items:flex-start;gap:16px;min-height:152px;padding:23px}.service-item>i{flex:none;display:grid;place-items:center;width:46px;height:46px;border-radius:15px;color:#2563eb;background:#eff6ff;font-size:22px}.service-item:nth-child(2)>i{color:#5b5ce2;background:#eef2ff}.service-item:nth-child(3)>i{color:#16a34a;background:#ecfdf3}.service-item h3{margin-bottom:6px;font-size:16px}.service-item p{color:var(--muted);font-size:13px;line-height:1.55}.service-item a{display:inline-block;margin-top:11px;color:#2563eb;font-size:12px;font-weight:800;text-decoration:none}.process-row{display:grid;grid-template-columns:repeat(3,1fr);gap:0;padding:6px;border-radius:20px;background:rgba(255,255,255,.5);border:1px solid rgba(255,255,255,.82)}.process-item{display:flex;align-items:center;gap:13px;padding:16px 20px;border-right:1px solid rgba(148,163,184,.18)}.process-item:last-child{border-right:0}.process-num{display:grid;place-items:center;width:34px;height:34px;flex:none;border-radius:50%;color:#fff;font-weight:800;font-size:13px;background:linear-gradient(135deg,#2563eb,#6366f1)}.process-item strong{display:block;font-size:13px;color:var(--dark)}.process-item span{display:block;margin-top:2px;color:var(--muted);font-size:11px}
  @media(max-width:900px){.portfolio-hero{grid-template-columns:1fr;min-height:unset}.hero-showcase{justify-content:flex-start}.showcase-panel{width:100%;max-width:none}.service-row{grid-template-columns:1fr}}@media(max-width:620px){.portfolio-hero{padding:28px 22px;border-radius:0 0 24px 24px}.portfolio-hero h1{font-size:48px}.metric-strip,.process-row{grid-template-columns:1fr}.metric-item,.process-item{border-right:0;border-bottom:1px solid rgba(148,163,184,.18)}.metric-item:last-child,.process-item:last-child{border-bottom:0}.portfolio-section-heading{display:block}.portfolio-section-heading p{margin-top:5px}}
</style>
<style>
  .portfolio-hero-actions .btn-light {
    background: #fff;
    color: #173da8;
    border: 1px solid rgba(255,255,255,.95);
    box-shadow: 0 12px 26px rgba(8,35,110,.3);
  }
  .portfolio-hero-actions .btn-light:hover {
    background: #eff6ff;
    color: #12327f;
    transform: translateY(-2px);
    box-shadow: 0 16px 30px rgba(8,35,110,.36);
  }
  .portfolio-hero-actions .btn-light:focus-visible {
    outline: 3px solid rgba(255,255,255,.85);
    outline-offset: 3px;
  }
</style>
<div class="portfolio-home">
  <section class="portfolio-hero"><div><div class="portfolio-kicker"><i class="bi bi-stars"></i> Titip Kilat / Platform logistik</div><h1>Kirim apa saja.<br>Jadi lebih mudah.</h1><p class="portfolio-hero-copy">Satu tempat untuk mengirim barang lokal, menitip belanja dari luar negeri, dan mengatur pembayaran dengan transparan.</p><div class="portfolio-hero-actions"><a href="{{ url('/orders/create') }}" class="btn btn-light"><i class="bi bi-plus-lg"></i> Buat pesanan</a><a href="{{ url('/orders') }}" class="btn btn-outline"><i class="bi bi-arrow-right"></i> Lihat pesanan</a></div></div><div class="hero-showcase"><div class="showcase-panel"><div class="showcase-panel-head"><span>STATUS PLATFORM</span><span class="showcase-live">Semua aktif</span></div><div class="showcase-number">24/7</div><div class="showcase-label">Koneksi pengiriman yang selalu siap</div><div class="showcase-rule"></div><div class="showcase-row"><span>Pengiriman lokal</span><strong>Siap</strong></div><div class="showcase-row" style="margin-top:12px"><span>Belanja global</span><strong>Siap</strong></div><div class="showcase-row" style="margin-top:12px"><span>Buku kas dompet</span><strong>Aman</strong></div></div></div></section>
  <section class="portfolio-section"><div class="metric-strip"><div class="metric-item"><i class="bi bi-receipt"></i><div><div class="metric-value">—</div><div class="metric-label">Total pesanan</div></div></div><div class="metric-item"><i class="bi bi-truck"></i><div><div class="metric-value">—</div><div class="metric-label">Kurir aktif</div></div></div><div class="metric-item"><i class="bi bi-airplane"></i><div><div class="metric-value">—</div><div class="metric-label">Perjalanan terbuka</div></div></div></div></section>
  <section class="portfolio-section"><div class="portfolio-section-heading"><div><div class="section-title">Satu platform, banyak kemungkinan</div><p>Layanan yang dibuat untuk kebutuhan titip harianmu.</p></div><a href="{{ url('/orders') }}" class="btn btn-outline btn-sm">Lihat pesanan <i class="bi bi-arrow-up-right"></i></a></div><div class="service-row"><article class="card service-item"><i class="bi bi-box-seam"></i><div><h3>Antar Warga</h3><p>Kurir terdekat membantu membeli dan mengantar kebutuhanmu.</p><a href="{{ url('/orders/create') }}">Buat pesanan <i class="bi bi-arrow-right"></i></a></div></article><article class="card service-item"><i class="bi bi-globe2"></i><div><h3>Jastip Global</h3><p>Temukan traveler dan titip barang dari perjalanan internasional.</p><a href="{{ url('/trips') }}">Lihat perjalanan <i class="bi bi-arrow-right"></i></a></div></article><article class="card service-item"><i class="bi bi-wallet2"></i><div><h3>Dompet Digital</h3><p>Pembayaran tercatat transparan dalam satu buku kas yang aman.</p><a href="{{ url('/wallet') }}">Buka dompet <i class="bi bi-arrow-right"></i></a></div></article></div></section>
  <section class="portfolio-section"><div class="portfolio-section-heading"><div><div class="section-title">Cara kerjanya</div><p>Dari pesan sampai selesai, sesederhana itu.</p></div></div><div class="process-row"><div class="process-item"><div class="process-num">1</div><div><strong>Pesan</strong><span>Isi detail barang</span></div></div><div class="process-item"><div class="process-num">2</div><div><strong>Proses</strong><span>Kurir atau traveler bekerja</span></div></div><div class="process-item"><div class="process-num">3</div><div><strong>Selesai</strong><span>Barang sampai dengan aman</span></div></div></div></section>
</div>
@endsection
