@extends('layouts.app')
@section('content')
<style>
  .trip-intro{padding:34px 38px;margin-bottom:22px;border-radius:26px;background:linear-gradient(120deg,#312e81,#4f46e5 55%,#7c3aed);color:#fff;box-shadow:0 20px 48px rgba(79,70,229,.18)}.trip-intro h1{color:#fff;font-size:clamp(32px,5vw,58px);letter-spacing:-.06em}.trip-intro p{margin-top:8px;color:rgba(255,255,255,.76);font-size:15px}.trip-list{display:none}.trip-line{display:grid;grid-template-columns:68px minmax(180px,.8fr) minmax(180px,1fr) auto;align-items:center;gap:22px;padding:22px 26px}.trip-route{display:flex;align-items:center;gap:10px;color:#1e40af;font-size:20px;font-weight:800}.trip-route i{font-size:17px;color:#818cf8}.trip-meta{display:flex;flex-wrap:wrap;gap:6px}.trip-code{color:var(--muted);font-size:11px}.trip-line .actions{display:flex;gap:8px}.trip-data-section .table-wrap{display:none}.trip-data-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.trip-data-card{display:flex;flex-direction:column;gap:16px;min-height:210px;padding:22px;border:1px solid rgba(99,102,241,.18);border-radius:20px;background:linear-gradient(145deg,rgba(255,255,255,.78),rgba(239,246,255,.7));box-shadow:0 14px 30px rgba(45,78,145,.08);transition:transform .2s,box-shadow .2s}.trip-data-card:hover{transform:translateY(-5px);box-shadow:0 20px 38px rgba(45,78,145,.14)}.trip-data-top{display:flex;justify-content:space-between;align-items:center}.trip-data-icon{display:grid;place-items:center;width:40px;height:40px;border-radius:13px;color:#4f46e5;background:#eef2ff;font-size:20px}.trip-data-card h3{color:#1e3a8a;font-size:19px}.trip-data-route{display:flex;align-items:center;gap:8px;color:#475569;font-size:12px}.trip-data-route i{color:#818cf8}.trip-data-detail{display:flex;justify-content:space-between;margin-top:auto;padding-top:14px;border-top:1px solid rgba(99,102,241,.14);color:var(--muted);font-size:11px}.trip-data-detail strong{color:#334155}@media(max-width:1000px){.trip-data-cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:800px){.trip-line{grid-template-columns:1fr 1fr;padding:20px}.trip-route{grid-column:1/-1}.trip-meta{grid-column:1}.trip-line .actions{grid-column:2;justify-content:flex-end}}@media(max-width:620px){.trip-data-cards{grid-template-columns:1fr}}@media(max-width:520px){.trip-intro{padding:28px 24px}.trip-line{grid-template-columns:1fr}.trip-route,.trip-meta,.trip-line .actions{grid-column:1}.trip-line .actions{justify-content:flex-start}}
</style>
<style>
  .trip-data-card{cursor:pointer}.trip-data-card:focus-visible{outline:3px solid rgba(79,70,229,.28);outline-offset:3px}.trip-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.trip-detail-item{padding:12px 13px;border-radius:13px;background:#f8fafc}.trip-detail-item small{display:block;color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.trip-detail-item strong{display:block;margin-top:4px;color:var(--dark);font-size:13px}.trip-product{margin-top:14px;padding-top:14px;border-top:1px solid var(--border)}.trip-product h3{font-size:13px}.trip-product p{margin-top:6px;white-space:pre-line;color:var(--slate);font-size:12px;line-height:1.6}.trip-product-image{display:block;width:100%;max-height:220px;margin-top:12px;object-fit:cover;border-radius:14px}.trip-detail-only{width:min(100%,680px)}@media(max-width:560px){.trip-detail-grid{grid-template-columns:1fr}}
</style>
<style>
  .trip-preview-image{width:100%;height:150px;object-fit:cover;border-radius:14px}.trip-preview-copy{color:var(--slate);font-size:12px;line-height:1.5}.trip-preview-copy strong{color:#4f46e5}.po-modal{display:none;position:fixed;inset:0;z-index:200;place-items:center;padding:20px;background:rgba(23,37,84,.42);backdrop-filter:blur(8px)}.po-modal.is-open{display:grid}.po-dialog{width:min(100%,460px);position:relative;padding:28px;border-radius:24px;background:rgba(255,255,255,.95);box-shadow:0 24px 70px rgba(23,37,84,.25)}.po-dialog h2{margin-bottom:6px}.po-dialog p{color:var(--muted);font-size:13px}.po-close{position:absolute;top:10px;right:10px;display:grid;place-items:center;width:44px;height:44px;padding:0;border:1px solid rgba(148,163,184,.16);border-radius:14px;background:var(--bg);color:var(--slate);font-size:25px;line-height:1;cursor:pointer;transition:background .18s ease,transform .18s ease}.po-close:hover{background:#e2e8f0;transform:scale(1.04)}.po-close:focus-visible{outline:3px solid rgba(37,99,235,.25);outline-offset:2px}.po-details{margin:20px 0;padding:15px;border-radius:14px;background:#eff6ff;color:#1e40af;font-size:13px;font-weight:700}.po-dialog .btn{width:100%;justify-content:center}
</style>
<div class="section-header" style="margin-bottom:26px"><div><div style="font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#4f46e5"><i class="bi bi-airplane"></i> Belanja global / Perjalanan</div><h1 style="font-size:clamp(32px,5vw,56px);letter-spacing:-.06em;margin-top:8px">Bawa dunia lebih dekat.</h1><p style="color:var(--muted);font-size:14px;margin-top:8px">Temukan traveler yang siap membawakan barang favoritmu dari perjalanan mereka.</p></div></div>
<form method="GET" class="card" style="display:flex;flex-wrap:wrap;gap:10px;align-items:end;margin-bottom:18px"><label style="flex:2;min-width:200px;color:var(--slate);font-size:11px;font-weight:700">Cari perjalanan<input class="form-input" name="q" value="{{ request('q') }}" placeholder="Kode atau kota"></label><label style="flex:1;min-width:150px;color:var(--slate);font-size:11px;font-weight:700">Tujuan<select class="form-input" name="destination"><option value="">Semua tujuan</option>@foreach(['Tokyo','Singapore','Seoul','Bangkok'] as $destination)<option @selected(request('destination')===$destination)>{{ $destination }}</option>@endforeach</select></label><label style="flex:1;min-width:130px;color:var(--slate);font-size:11px;font-weight:700">Kategori DP<select class="form-input" name="dp"><option value="">Semua DP</option><option value="0" @selected(request('dp')==='0')>Tanpa DP</option><option value="30" @selected(request('dp')==='30')>DP 30%</option><option value="50" @selected(request('dp')==='50')>DP 50%</option></select></label><button class="btn btn-primary" type="submit"><i class="bi bi-search"></i> Cari</button><a class="btn btn-outline" href="{{ url('/trips') }}">Reset</a></form>
<form method="GET" class="card" style="display:flex;justify-content:flex-end;gap:10px;align-items:center;margin-bottom:18px"><input type="hidden" name="q" value="{{ request('q') }}"><input type="hidden" name="destination" value="{{ request('destination') }}"><input type="hidden" name="dp" value="{{ request('dp') }}"><label style="color:var(--slate);font-size:11px;font-weight:700">Urutkan<select class="form-input" name="sort"><option value="soonest" @selected(request('sort','soonest')==='soonest')>Keberangkatan terdekat</option><option value="latest" @selected(request('sort')==='latest')>Keberangkatan terakhir</option><option value="destination" @selected(request('sort')==='destination')>Tujuan A–Z</option></select></label><button class="btn btn-outline btn-sm" type="submit">Terapkan</button></form>
<style>form.card:has(select[name="sort"]):not(.trip-filter-bar){display:none!important}.trip-filter-bar{display:flex!important;flex-wrap:wrap;align-items:end!important;gap:10px!important;padding:18px!important;background:rgba(255,255,255,.72)!important;border:1px solid rgba(255,255,255,.9)!important;box-shadow:0 12px 28px rgba(45,78,145,.08)!important}.trip-filter-bar label{color:var(--slate);font-size:11px;font-weight:700}.trip-filter-bar .form-input{margin-top:6px}</style>
<script>document.addEventListener('DOMContentLoaded',()=>{const filterForm=document.querySelector('form.card');const sortForm=[...document.querySelectorAll('form.card')].find(form=>form.querySelector('select[name="sort"]'));if(!filterForm||!sortForm)return;filterForm.classList.add('trip-filter-bar');const sortLabel=sortForm.querySelector('label');const applyButton=sortForm.querySelector('button[type="submit"]');if(sortLabel)filterForm.append(sortLabel);if(applyButton)filterForm.append(applyButton);sortForm.remove();});</script>
<div class="trip-list"><article class="card trip-line"><i class="bi bi-airplane-engines" style="font-size:30px;color:#6366f1"></i><div><div class="trip-route">Jakarta <i class="bi bi-arrow-right"></i> Tokyo</div><div class="trip-code">TRIP-DEMO001 · 15 Sep 2026</div></div><div class="trip-meta"><span class="badge badge-red">DP 50%</span><span class="badge badge-slate">Wajib DP</span></div><div class="actions"><a href="{{ url('/orders/create') }}" class="btn btn-accent btn-sm" data-po-modal>Buat PO</a><button class="btn btn-outline btn-sm" type="button" data-detail-modal>Rincian</button></div></article><article class="card trip-line"><i class="bi bi-airplane-engines" style="font-size:30px;color:#6366f1"></i><div><div class="trip-route">Jakarta <i class="bi bi-arrow-right"></i> Singapore</div><div class="trip-code">TRIP-DEMO002 · 20 Sep 2026</div></div><div class="trip-meta"><span class="badge badge-orange">DP 30%</span><span class="badge badge-slate">Opsional DP</span></div><div class="actions"><a href="{{ url('/orders/create') }}" class="btn btn-accent btn-sm" data-po-modal>Buat PO</a><button class="btn btn-outline btn-sm" type="button" data-detail-modal>Rincian</button></div></article><article class="card trip-line"><i class="bi bi-airplane-engines" style="font-size:30px;color:#6366f1"></i><div><div class="trip-route">Jakarta <i class="bi bi-arrow-right"></i> Seoul</div><div class="trip-code">TRIP-DEMO003 · 1 Oct 2026</div></div><div class="trip-meta"><span class="badge badge-green">DP 0%</span><span class="badge badge-slate">Tanpa DP</span></div><div class="actions"><a href="{{ url('/orders/create') }}" class="btn btn-accent btn-sm" data-po-modal>Buat PO</a><button class="btn btn-outline btn-sm" type="button" data-detail-modal>Rincian</button></div></article></div>
<div class="po-modal" id="po-modal" role="dialog" aria-modal="true" aria-labelledby="po-modal-title"><div class="po-dialog"><button class="po-close" type="button" aria-label="Tutup">&times;</button><h2 id="po-modal-title">Buat Pre-order Internasional</h2><p>Trip yang kamu pilih:</p><div class="po-details" id="po-trip-details"></div><p>Detail barang dan pembayaran DP akan diisi pada form pre-order.</p><a class="btn btn-accent" href="{{ url('/orders/create') }}" style="margin-top:20px">Lanjutkan buat PO <i class="bi bi-arrow-right"></i></a></div></div>
<div class="po-modal" id="trip-detail-modal" role="dialog" aria-modal="true" aria-labelledby="trip-detail-title"><div class="po-dialog trip-detail-only"><button class="po-close" type="button" aria-label="Tutup">&times;</button><h2 id="trip-detail-title">Rincian perjalanan</h2><div class="po-details" id="trip-detail-content"></div><div class="trip-modal-actions"><button class="btn btn-outline" type="button" id="trip-detail-chat"><i class="bi bi-chat-dots"></i> Chat traveler</button><a class="btn btn-primary" id="trip-detail-order" href="{{ url('/orders/create') }}"><i class="bi bi-bag-check"></i> Order now</a></div><button class="btn btn-outline" type="button" data-detail-close style="margin-top:12px">Tutup</button></div></div>
<style>.trip-modal-actions{display:flex;gap:10px;margin-top:18px}.trip-modal-actions>*{flex:1;justify-content:center}@media(max-width:460px){.trip-modal-actions{display:grid}}</style>
<script>
  (() => { const modal=document.getElementById('po-modal'); const details=document.getElementById('po-trip-details'); const close=modal.querySelector('.po-close'); const hide=()=>{modal.classList.remove('is-open');document.body.style.overflow='';}; document.querySelectorAll('[data-po-modal]').forEach(trigger=>trigger.addEventListener('click',event=>{event.preventDefault();details.textContent=trigger.closest('.trip-line').querySelector('.trip-route').textContent.trim()+' · '+trigger.closest('.trip-line').querySelector('.trip-code').textContent.trim();modal.classList.add('is-open');document.body.style.overflow='hidden';close.focus();})); close.addEventListener('click',hide); modal.addEventListener('click',event=>{if(event.target===modal)hide();}); const detailModal=document.getElementById('trip-detail-modal'); const detailContent=document.getElementById('trip-detail-content'); const detailClose=detailModal.querySelector('.po-close'); const hideDetail=()=>{detailModal.classList.remove('is-open');document.body.style.overflow='';}; document.querySelectorAll('[data-detail-modal]').forEach(trigger=>trigger.addEventListener('click',()=>{const card=trigger.closest('.trip-line'); detailContent.textContent=card.querySelector('.trip-route').textContent.trim()+' · '+card.querySelector('.trip-code').textContent.trim()+' · '+Array.from(card.querySelectorAll('.trip-meta .badge')).map(item=>item.textContent.trim()).join(' · '); detailModal.classList.add('is-open');document.body.style.overflow='hidden';detailClose.focus();})); detailClose.addEventListener('click',hideDetail); detailModal.querySelector('[data-detail-close]').addEventListener('click',hideDetail); detailModal.addEventListener('click',event=>{if(event.target===detailModal)hideDetail();}); document.addEventListener('keydown',event=>{if(event.key==='Escape'){hide();hideDetail();}}); })();
</script>
<section class="portfolio-section trip-data-section"><div class="portfolio-section-heading"><div><div class="section-title">Perjalanan tersedia</div><p>Pilih perjalanan yang paling sesuai untuk pre-order kamu.</p></div></div><div class="trip-data-cards">@forelse($trips as $trip)<article class="trip-data-card"><div class="trip-data-top"><span class="trip-data-icon"><i class="bi bi-airplane-engines"></i></span><span class="badge {{ $trip->dp_percent > 0 ? 'badge-orange' : 'badge-green' }}">{{ $trip->dp_percent > 0 ? 'DP '.$trip->dp_percent.'%' : 'Tanpa DP' }}</span></div><div><h3>{{ $trip->code }}</h3><div class="trip-data-route">{{ $trip->origin }} <i class="bi bi-arrow-right"></i> {{ $trip->destination }}</div></div><div class="trip-data-detail"><span>Keberangkatan</span><strong>{{ $trip->departure_at->format('d M Y') }}</strong></div></article>@empty<div class="card" style="grid-column:1/-1;text-align:center;color:var(--muted);padding:40px">Belum ada perjalanan tersedia.</div>@endforelse</div><div class="pagination-wrap">{{ $trips->links() }}</div><div class="card table-wrap"><table class="users-table"><thead><tr><th>Trip</th><th>Rute</th><th>Keberangkatan</th><th>DP</th></tr></thead><tbody>@foreach($trips as $trip)<tr><td>{{ $trip->code }}</td><td>{{ $trip->origin }} → {{ $trip->destination }}</td><td>{{ $trip->departure_at->format('d M Y') }}</td><td>{{ $trip->dp_percent }}%</td></tr>@endforeach</tbody></table></div></section>
<style>.trip-detail-only{max-height:90vh;overflow-y:auto;overscroll-behavior:contain}@media(max-width:560px){.trip-detail-only{max-height:calc(100vh - 32px)}}
</style>
<style>.trip-product-list{display:grid;gap:9px;margin-top:10px}.trip-product-item{padding:12px 13px;border:1px solid rgba(99,102,241,.14);border-radius:13px;background:#f8fafc}.trip-product-item header{display:flex;justify-content:space-between;gap:10px;align-items:start}.trip-product-item strong{color:#1e3a8a;font-size:13px}.trip-product-price{white-space:nowrap;color:#4f46e5;font-size:12px;font-weight:800}.trip-product-item p{margin-top:4px!important;color:var(--muted)!important;font-size:11px!important;line-height:1.45!important}.trip-starting-price{color:#4f46e5!important;font-size:12px!important;font-weight:800!important}</style>
@php
  $tripDetails = $trips->getCollection()->map(function ($trip) {
      return [
          'id' => $trip->id,
          'code' => $trip->code,
          'origin' => $trip->origin,
          'destination' => $trip->destination,
          'departure' => $trip->departure_at?->format('d M Y, H:i'),
          'arrival' => $trip->arrival_at?->format('d M Y, H:i'),
          'dp' => $trip->dp_percent,
          'dpRequired' => $trip->dp_required,
          'traveler' => $trip->traveler?->name ?? 'Traveler',
          'email' => $trip->traveler?->email ?? '',
          'product' => $trip->product_details,
          'image' => $trip->product_image,
          'products' => $trip->product_items ?? [],
          'conversationCount' => $trip->conversations_count ?? 0,
      ];
  })->values();
@endphp
<script>
  (() => {
    const trips = @json($tripDetails);
    trips.forEach(trip=>{const card=[...document.querySelectorAll('.trip-data-card')].find(item=>item.querySelector('h3')?.textContent.trim()===trip.code);const products=trip.products||[];const start=products.length?Math.min(...products.map(item=>Number(item.price)||0)):null;if(card&&!card.querySelector('.trip-preview-image')){card.insertAdjacentHTML('afterbegin',`${trip.image?`<img class="trip-preview-image" src="${trip.image}" alt="Produk jastip ${trip.traveler}">`:''}<div class="trip-preview-copy"><strong>${trip.traveler}</strong> · ${products.length} produk tersedia</div>${start!==null?`<div class="trip-starting-price">Mulai dari Rp ${start.toLocaleString('id-ID')}</div>`:''}`);}});
    const modal=document.getElementById('trip-detail-modal'); const content=document.getElementById('trip-detail-content'); const close=modal?.querySelector('.po-close'); const closeAction=modal?.querySelector('[data-detail-close]'); const hide=()=>{modal?.classList.remove('is-open');document.body.style.overflow='';}; close?.addEventListener('click',hide); closeAction?.addEventListener('click',hide); modal?.addEventListener('click',event=>{if(event.target===modal)hide();}); document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal?.classList.contains('is-open'))hide();});
    const open=card=>{const trip=trips.find(item=>item.code===card.querySelector('h3')?.textContent.trim());if(!trip)return;const products=trip.products||[];const productList=products.length?products.map(item=>`<article class="trip-product-item"><header><strong>${item.name}</strong><span class="trip-product-price">Rp ${Number(item.price||0).toLocaleString('id-ID')}</span></header><p>${item.description||'Detail produk belum ditambahkan.'}</p></article>`).join(''):'<p>Traveler belum menambahkan daftar produk jastip.</p>';content.innerHTML=`<div class="trip-detail-grid"><div class="trip-detail-item"><small>Traveler</small><strong>${trip.traveler}</strong><span style="display:block;margin-top:3px;color:var(--muted);font-size:11px">${trip.email}</span></div><div class="trip-detail-item"><small>Rute</small><strong>${trip.origin} → ${trip.destination}</strong></div><div class="trip-detail-item"><small>Berangkat</small><strong>${trip.departure||'Belum diatur'}</strong></div><div class="trip-detail-item"><small>Tiba</small><strong>${trip.arrival||'Belum diatur'}</strong></div><div class="trip-detail-item"><small>DP</small><strong>${trip.dpRequired ? trip.dp+'%' : 'Tanpa DP'}</strong></div></div><div class="trip-product"><h3>Produk jastip yang tersedia</h3><div class="trip-product-list">${productList}</div>${trip.image?`<img class="trip-product-image" src="${trip.image}" alt="Contoh produk jastip dari ${trip.traveler}">`:''}</div>`;modal.classList.add('is-open');document.body.style.overflow='hidden';close?.focus();};
    document.querySelectorAll('.trip-data-card').forEach(card=>{card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label','Lihat detail '+(card.querySelector('h3')?.textContent.trim()||'perjalanan'));card.addEventListener('click',()=>open(card));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open(card);}});});
    window.addEventListener('request-trip-details', event=>{window.selectedTrip=event.detail;const orderLink=document.getElementById('trip-detail-order');if(orderLink)orderLink.href=`/orders/create?trip_reference=${encodeURIComponent(event.detail.code)}`;const card=[...document.querySelectorAll('.trip-data-card')].find(item=>item.querySelector('h3')?.textContent.trim()===event.detail.code);if(card)card.click();});document.getElementById('trip-detail-chat')?.addEventListener('click',()=>{if(window.selectedTrip)window.dispatchEvent(new CustomEvent('open-trip-chat',{detail:window.selectedTrip}));});
  })();
</script>
<div class="chat-modal" id="trip-chat-modal" role="dialog" aria-modal="true" aria-labelledby="trip-chat-title"><div class="chat-dialog"><button class="chat-close" type="button" aria-label="Tutup">&times;</button><div class="chat-heading"><div class="trip-data-icon"><i class="bi bi-chat-dots"></i></div><div><h2 id="trip-chat-title">Chat perjalanan</h2><p id="trip-chat-subtitle">Tanyakan detail barang kepada traveler.</p></div></div><div class="chat-messages" id="trip-chat-messages"><div class="chat-empty">Belum ada pesan.</div></div><form id="trip-chat-form" class="chat-form"><input id="trip-chat-input" name="body" maxlength="2000" required placeholder="Tulis pesan…"><button class="btn btn-primary" type="submit"><i class="bi bi-send"></i></button></form></div></div>
<style>.chat-modal{display:none;position:fixed;inset:0;z-index:240;place-items:center;padding:20px;background:rgba(23,37,84,.42);backdrop-filter:blur(8px)}.chat-modal.is-open{display:grid}.chat-dialog{display:flex;flex-direction:column;width:min(100%,500px);height:min(680px,calc(100vh - 40px));padding:22px;border-radius:24px;background:var(--surface);box-shadow:0 24px 70px rgba(23,37,84,.25)}.chat-close{align-self:flex-end;width:42px;height:42px;border:0;border-radius:13px;background:var(--bg);color:var(--slate);font-size:24px;cursor:pointer}.chat-heading{display:flex;align-items:center;gap:12px;padding-bottom:16px;border-bottom:1px solid var(--border)}.chat-heading h2{font-size:18px}.chat-heading p{margin-top:3px;color:var(--muted);font-size:12px}.chat-messages{display:flex;flex:1;flex-direction:column;gap:10px;overflow-y:auto;padding:18px 4px}.chat-empty{text-align:center;margin:auto;color:var(--muted);font-size:13px}.chat-bubble{max-width:82%;padding:10px 12px;border-radius:15px;background:#eef2ff;color:#27356b;font-size:13px;line-height:1.45}.chat-bubble.mine{align-self:flex-end;background:#2563eb;color:#fff}.chat-bubble small{display:block;margin-top:4px;opacity:.65;font-size:10px}.chat-form{display:flex;gap:8px;padding-top:14px;border-top:1px solid var(--border)}.chat-form input{flex:1;min-width:0;padding:12px 14px;border:1px solid var(--border);border-radius:13px;background:var(--surface);color:var(--dark);font:inherit}.chat-form .btn{width:46px;justify-content:center;padding:0}@media(max-width:560px){.chat-dialog{height:calc(100vh - 24px);padding:17px}}</style>
<script>
  (() => {
    const trips = @json($tripDetails); const role = @json(auth()->user()->role?->name); const modal = document.getElementById('trip-chat-modal'); const messages = document.getElementById('trip-chat-messages'); const form = document.getElementById('trip-chat-form'); const input = document.getElementById('trip-chat-input'); let activeTrip = null; let activeConversation = null;
    const render = list => { messages.textContent=''; if (!list?.length) { messages.innerHTML='<div class="chat-empty">Belum ada pesan. Mulai percakapan.</div>'; return; } list.forEach(item=>{const bubble=document.createElement('div');bubble.className=`chat-bubble${Number(item.sender_id)===Number({{ auth()->id() }})?' mine':''}`;bubble.textContent=item.body;const meta=document.createElement('small');meta.textContent=item.sender?.name||'Pengguna';bubble.appendChild(meta);messages.appendChild(bubble);});messages.scrollTop=messages.scrollHeight; };
    const load = async trip => { const response=await fetch(`/trips/${trip.id}/chat`,{headers:{Accept:'application/json'}});if(!response.ok){window.showToast?.('Chat tidak tersedia.','error');return;}const data=await response.json();if(role==='TRAVELER'){const conversation=data.conversations?.[0];activeConversation=conversation?.id||null;render(conversation?.messages||[]);document.getElementById('trip-chat-subtitle').textContent=conversation?`Chat dengan ${conversation.customer?.name||'pelanggan'}`:'Belum ada pelanggan yang menghubungi.';}else{activeConversation=data.conversation?.id||null;render(data.conversation?.messages||[]);document.getElementById('trip-chat-subtitle').textContent=`Chat dengan ${trip.traveler||'traveler'}`;}};
    const open = async trip => {activeTrip=trip;document.getElementById('trip-chat-title').textContent=`Chat · ${trip.code}`;messages.innerHTML='<div class="chat-empty">Memuat percakapan…</div>';modal.classList.add('is-open');document.body.style.overflow='hidden';await load(trip);input.focus();};
    document.querySelectorAll('.trip-data-card').forEach(card=>{const trip=trips.find(item=>item.code===card.querySelector('h3')?.textContent.trim());if(!trip)return;const button=document.createElement('button');button.type='button';button.className='btn btn-outline btn-sm';button.style.cssText='width:100%;justify-content:center;margin-top:auto';button.innerHTML='<i class="bi bi-eye"></i> View details';button.addEventListener('click',event=>{event.stopPropagation();window.dispatchEvent(new CustomEvent('request-trip-details',{detail:trip}));});card.appendChild(button);});
    form?.addEventListener('submit',async event=>{event.preventDefault();if(!activeTrip)return;const body=input.value.trim();if(!body)return;const response=await fetch(`/trips/${activeTrip.id}/chat`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({body,conversation_id:activeConversation})});if(!response.ok){window.showToast?.('Pesan gagal dikirim.','error');return;}const data=await response.json();if(data.message){activeConversation ||= data.message.conversation_id;input.value='';await load(activeTrip);}});
    const hide=()=>{modal?.classList.remove('is-open');document.body.style.overflow='';};modal?.querySelector('.chat-close')?.addEventListener('click',hide);modal?.addEventListener('click',event=>{if(event.target===modal)hide();});document.addEventListener('keydown',event=>{if(event.key==='Escape')hide();});window.addEventListener('open-trip-chat',event=>open(event.detail));setInterval(()=>{if(modal?.classList.contains('is-open')&&activeTrip)load(activeTrip);},5000);
  })();
</script>
@endsection
