@extends('layouts.app')
@section('content')
<style>
 .wallet-hero{display:grid;grid-template-columns:1fr auto;align-items:center;gap:24px;padding:34px 40px;margin-bottom:16px;border-radius:28px;color:#fff;background:linear-gradient(120deg,#1d4ed8,#4f46e5);box-shadow:0 24px 58px rgba(37,99,235,.2)}.wallet-hero .label{color:rgba(255,255,255,.7);font-size:13px}.wallet-hero .amount{margin:5px 0 8px;font-size:52px;font-weight:800;line-height:1;letter-spacing:-.06em}.wallet-hero .note{color:rgba(255,255,255,.68);font-size:12px}.wallet-actions{display:flex;gap:9px;margin-top:22px}.wallet-actions .btn{color:#fff;background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.25)}.wallet-actions .btn:first-child{background:#fff;color:#2563eb}.wallet-mark{font-size:92px;opacity:.17}.wallet-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:28px}.wallet-stat{display:flex;align-items:center;gap:13px;padding:18px 20px}.wallet-stat i{display:grid;place-items:center;width:40px;height:40px;border-radius:14px;background:#eff6ff;color:#2563eb;font-size:18px}.wallet-stat strong{display:block;color:var(--dark);font-size:18px}.wallet-stat span{display:block;color:var(--muted);font-size:12px;margin-top:2px}@media(max-width:620px){.wallet-hero{grid-template-columns:1fr;padding:28px 24px}.wallet-mark{display:none}.wallet-stats{grid-template-columns:1fr}}
 .wallet-modal{display:none;position:fixed;inset:0;z-index:200;place-items:center;padding:20px;background:rgba(23,37,84,.42);backdrop-filter:blur(8px)}.wallet-modal.is-open{display:grid}.wallet-dialog{width:min(100%,520px);position:relative;padding:28px;border:1px solid rgba(255,255,255,.9);border-radius:24px;background:rgba(255,255,255,.95);box-shadow:0 24px 70px rgba(23,37,84,.25);animation:ui-rise .35s ease-out}.wallet-dialog h2{margin-bottom:6px}.wallet-dialog p{color:var(--muted);font-size:13px}.wallet-close{position:absolute;top:16px;right:16px;width:32px;height:32px;border:0;border-radius:50%;background:var(--bg);color:var(--slate);font-size:20px;cursor:pointer}.wallet-form{display:grid;gap:14px;margin-top:20px}.wallet-form label{display:grid;gap:6px;color:var(--slate);font-size:12px;font-weight:700}.wallet-form input{width:100%;padding:12px 14px;border:1px solid var(--border);border-radius:12px;font:inherit}.payment-methods{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:18px}.payment-method{display:flex;align-items:center;gap:10px;padding:12px;border:1px solid var(--border);border-radius:13px;background:#fff;color:var(--slate);font:inherit;font-size:12px;font-weight:700;text-align:left;cursor:pointer;transition:all .18s}.payment-method i{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#eff6ff;color:#2563eb;font-size:16px}.payment-method:hover,.payment-method.active{border-color:#6366f1;background:#f5f3ff;color:#4338ca;transform:translateY(-2px)}.payment-method.active{box-shadow:0 0 0 3px rgba(99,102,241,.1)}.payment-method small{display:block;margin-top:2px;color:var(--muted);font-size:10px;font-weight:500}.payment-instruction{padding:13px;border-radius:13px;background:#eff6ff;color:#1e40af;font-size:11px;line-height:1.5}.payment-instruction strong{display:block;margin-bottom:3px;font-size:12px}.wallet-qr{display:grid;place-items:center;width:176px;height:176px;margin:18px auto;padding:12px;border:8px solid #fff;border-radius:14px;background:repeating-linear-gradient(45deg,#172554 0 5px,#fff 5px 9px),repeating-linear-gradient(-45deg,transparent 0 6px,#172554 6px 10px);box-shadow:0 8px 24px rgba(23,37,84,.14)}.wallet-qr:after{content:'TK';display:grid;place-items:center;width:42px;height:42px;border:5px solid #fff;border-radius:10px;background:#2563eb;color:#fff;font-weight:800}.scan-frame{position:relative;display:grid;place-items:center;width:220px;height:180px;margin:20px auto;border:2px solid #2563eb;border-radius:18px;background:#eff6ff;overflow:hidden}.scan-frame:before{content:'';position:absolute;left:14px;right:14px;height:2px;background:#22c55e;box-shadow:0 0 12px #22c55e;animation:scan-line 2s ease-in-out infinite}.scan-frame i{color:#2563eb;font-size:48px}.wallet-actions .scan-wallet{background:rgba(255,255,255,.12)}@keyframes scan-line{0%,100%{top:20px}50%{top:156px}}@media(max-width:520px){.payment-methods{grid-template-columns:1fr}}
</style>
<div class="wallet-hero"><div><div class="label">SALDO TERSEDIA</div><div class="amount">Rp {{ number_format($wallet->balance, 0, ',', '.') }}</div><div class="note">Isi saldo dikenakan biaya layanan Rp1.000</div><div class="wallet-actions"><button class="btn" type="button" data-wallet-modal><i class="bi bi-plus-lg"></i> Isi saldo</button><button class="btn scan-wallet" type="button" data-scan-wallet-modal><i class="bi bi-qr-code-scan"></i> Scan QRIS</button></div></div><i class="bi bi-wallet2 wallet-mark"></i></div>
<div class="wallet-modal" id="wallet-modal" role="dialog" aria-modal="true" aria-labelledby="wallet-modal-title"><div class="wallet-dialog"><button class="wallet-close" type="button" aria-label="Tutup">&times;</button><h2 id="wallet-modal-title">Isi saldo dompet</h2><p>Pilih metode pembayaran dan masukkan nominal top-up.</p><form class="wallet-form" method="POST" action="{{ route('wallet.top-up') }}" data-wallet-client-form>@csrf<label>Nominal isi saldo<input name="amount" type="number" min="1000" step="1000" placeholder="100000" required></label><div class="payment-methods"><button type="button" class="payment-method active" data-payment="Bank Transfer"><i class="bi bi-bank"></i><span>Bank Transfer<small>BCA, BNI, Mandiri</small></span></button><button type="button" class="payment-method" data-payment="Virtual Account"><i class="bi bi-credit-card-2-front"></i><span>Virtual Account<small>Nomor otomatis</small></span></button><button type="button" class="payment-method" data-payment="E-Wallet"><i class="bi bi-phone"></i><span>E-Wallet<small>GoPay, OVO, DANA</small></span></button><button type="button" class="payment-method" data-payment="QRIS"><i class="bi bi-qr-code"></i><span>QRIS<small>Scan untuk bayar</small></span></button></div><input type="hidden" name="payment_method" value="Bank Transfer"><div class="payment-instruction" id="payment-instruction"><strong>Bank Transfer</strong>Instruksi pembayaran akan ditampilkan setelah nominal dikonfirmasi.</div><button class="btn btn-primary" type="submit" style="justify-content:center">Lanjutkan pembayaran <i class="bi bi-arrow-right"></i></button></form></div></div>
<div class="wallet-modal" id="send-wallet-modal" role="dialog" aria-modal="true" aria-labelledby="send-wallet-modal-title"><div class="wallet-dialog"><button class="wallet-close" type="button" aria-label="Tutup">&times;</button><h2 id="send-wallet-modal-title">Kirim saldo</h2><p>Masukkan penerima dan nominal saldo yang ingin dikirim.</p><form class="wallet-form" action="{{ url('/wallet') }}" method="get"><label>Email penerima<input name="recipient" type="email" placeholder="penerima@email.com" required></label><label>Nominal kirim<input name="amount" type="number" min="1000" step="1000" placeholder="100000" required></label><button class="btn btn-primary" type="submit" style="justify-content:center">Lanjutkan <i class="bi bi-arrow-right"></i></button></form></div></div>
<div class="wallet-modal" id="scan-wallet-modal" role="dialog" aria-modal="true" aria-labelledby="scan-wallet-title"><div class="wallet-dialog" style="text-align:center"><button class="wallet-close" type="button" aria-label="Tutup">&times;</button><h2 id="scan-wallet-title">Scan QRIS</h2><p>Arahkan kamera ke kode QRIS untuk memeriksa atau membayar saldo.</p><div class="scan-frame"><i class="bi bi-qr-code-scan"></i></div><button class="btn btn-primary" type="button" style="width:100%;justify-content:center" data-scan-start>Mulai scan</button></div></div>
<script>
  (() => {
    const topup=document.getElementById('wallet-modal'); const scan=document.getElementById('scan-wallet-modal');
    const hide=modal=>{modal?.classList.remove('is-open');document.body.style.overflow='';};
    [{modal:topup,trigger:document.querySelector('[data-wallet-modal]')},{modal:scan,trigger:document.querySelector('[data-scan-wallet-modal]')}].forEach(({modal,trigger})=>{if(!modal||!trigger)return;trigger.addEventListener('click',event=>{event.preventDefault();modal.classList.add('is-open');document.body.style.overflow='hidden';modal.querySelector('input')?.focus();});modal.querySelector('.wallet-close')?.addEventListener('click',()=>hide(modal));modal.addEventListener('click',event=>{if(event.target===modal)hide(modal);});});
    const instruction=document.getElementById('payment-instruction'); const hiddenMethod=topup?.querySelector('[name="payment_method"]'); const instructions={'Bank Transfer':'Instruksi pembayaran akan ditampilkan setelah nominal dikonfirmasi.','Virtual Account':'Nomor Virtual Account unik akan dibuat setelah nominal dikonfirmasi.','E-Wallet':'Kamu akan diarahkan ke aplikasi e-wallet pilihanmu untuk menyelesaikan pembayaran.','QRIS':'Kode QRIS akan ditampilkan setelah nominal dikonfirmasi dan bisa dipindai dari aplikasi pembayaran.'}; topup?.querySelectorAll('[data-payment]').forEach(method=>method.addEventListener('click',()=>{topup.querySelectorAll('[data-payment]').forEach(item=>item.classList.remove('active'));method.classList.add('active');hiddenMethod.value=method.dataset.payment;instruction.innerHTML=`<strong>${method.dataset.payment}</strong>${instructions[method.dataset.payment]}`;}));
    topup?.querySelector('form')?.addEventListener('submit',()=>{hide(topup);});
    scan?.querySelector('[data-scan-start]')?.addEventListener('click',()=>window.showToast?.('Akses kamera QRIS siap dihubungkan.'));
    document.addEventListener('keydown',event=>{if(event.key==='Escape'){hide(topup);hide(scan);}});
  })();
</script>
<div class="wallet-stats"><div class="card wallet-stat"><i class="bi bi-graph-up-arrow"></i><div><strong>Rp {{ number_format($totalTopUp, 0, ',', '.') }}</strong><span>Total isi saldo</span></div></div><div class="card wallet-stat"><i class="bi bi-graph-down-arrow"></i><div><strong>Rp {{ number_format($totalSpent, 0, ',', '.') }}</strong><span>Total pengeluaran</span></div></div><div class="card wallet-stat"><i class="bi bi-arrow-repeat"></i><div><strong>{{ $transactions->count() }}</strong><span>Transaksi</span></div></div></div>
<div class="portfolio-section-heading"><div><div class="section-title">Riwayat transaksi</div><p>Semua aktivitas dompet tercatat di sini.</p></div></div><div class="card">@forelse($transactions as $transaction)<div class="setting-row"><div class="setting-label"><strong>{{ $transaction->description }}</strong><span>{{ $transaction->created_at?->format('d M Y, H:i') }} · {{ $transaction->reference }}</span></div><span class="setting-value" style="color:{{ $transaction->credit > 0 ? '#16a34a' : '#dc2626' }}">{{ $transaction->credit > 0 ? '+' : '-' }} Rp {{ number_format($transaction->credit > 0 ? $transaction->credit : $transaction->debit, 0, ',', '.') }}</span></div>@empty<div class="empty"><div class="empty-icon"><i class="bi bi-receipt"></i></div><div class="empty-title">Belum ada aktivitas</div><p>Riwayat transaksi dompet akan muncul di sini.</p></div>@endforelse</div>
@endsection
