<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ $code ?? 'Error' }} · Titip Kilat</title>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500;600;700;800&display=swap" rel="stylesheet">
  <style>
    :root{font-family:'Plus Jakarta Sans',system-ui,sans-serif;color:#172554;background:#eef4ff}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 12% 18%,#dbeafe 0,transparent 32%),radial-gradient(circle at 88% 82%,#e0e7ff 0,transparent 34%),#f8fbff}.error-shell{position:relative;width:min(100%,920px);overflow:hidden;padding:clamp(30px,6vw,72px);border:1px solid rgba(255,255,255,.9);border-radius:32px;background:rgba(255,255,255,.78);box-shadow:0 28px 80px rgba(37,70,145,.16);backdrop-filter:blur(20px)}.error-shell:before{content:'';position:absolute;right:-90px;top:-100px;width:290px;height:290px;border:1px solid rgba(99,102,241,.18);border-radius:50%;box-shadow:0 0 0 28px rgba(129,140,248,.08),0 0 0 58px rgba(96,165,250,.06)}.brand{display:inline-flex;align-items:center;gap:10px;color:#2563eb;font-size:14px;font-weight:800;letter-spacing:.02em}.brand-mark{display:grid;place-items:center;width:34px;height:34px;border-radius:11px;color:#fff;background:linear-gradient(135deg,#2563eb,#7c3aed);box-shadow:0 8px 18px rgba(37,99,235,.25)}.error-code{position:relative;margin:38px 0 4px;color:#4f46e5;font-size:clamp(64px,14vw,142px);font-weight:800;letter-spacing:-.1em;line-height:.9}.error-title{position:relative;margin:20px 0 8px;font-size:clamp(24px,4vw,38px);letter-spacing:-.05em}.error-copy{position:relative;max-width:560px;color:#64748b;font-size:14px;line-height:1.7}.error-actions{position:relative;display:flex;flex-wrap:wrap;gap:10px;margin-top:28px}.error-button{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 18px;border-radius:13px;text-decoration:none;font:inherit;font-size:13px;font-weight:800;cursor:pointer}.error-primary{color:#fff;background:linear-gradient(135deg,#2563eb,#4f46e5);box-shadow:0 10px 20px rgba(37,99,235,.2)}.error-secondary{color:#334155;background:#fff;border:1px solid #dbe4f3}.error-meta{position:relative;margin-top:38px;color:#94a3b8;font-size:11px}@media(max-width:560px){.error-shell{border-radius:24px;padding:30px 24px}.error-actions{display:grid}.error-button{width:100%}}
  </style>
</head>
<body><main class="error-shell"><div class="brand"><span class="brand-mark">⚡</span> Titip Kilat</div><div class="error-code">{{ $code }}</div><h1 class="error-title">{{ $title }}</h1><p class="error-copy">{{ $message }}</p><div class="error-actions"><a class="error-button error-primary" href="{{ url('/') }}">Kembali ke beranda</a>@if(auth()->guest())<a class="error-button error-secondary" href="{{ route('login') }}">Masuk ke akun</a>@else<button class="error-button error-secondary" type="button" onclick="history.back()">Kembali ke halaman sebelumnya</button>@endif</div><div class="error-meta">Jika masalah terus terjadi, catat waktu dan alamat halaman ini saat menghubungi tim Titip Kilat.</div></main></body>
</html>
