<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\Level;
use App\Models\User;
use App\Models\ActivityLog;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index(Request $request) { $tab=$request->query('tab','users'); $roleOptions=Role::orderBy('name')->get(); $levelOptions=Level::orderBy('sort_order')->get(); $roles=$tab === 'roles' ? Role::withCount('users')->when($request->filled('q'),fn($query)=>$query->where('name','like','%'.$request->q.'%'))->orderBy($request->query('sort')==='users' ? 'users_count' : 'name',$request->query('sort')==='users' ? 'desc' : 'asc')->paginate(10)->withQueryString() : $roleOptions; $userSorts=['latest'=>'created_at','oldest'=>'created_at','name'=>'name','email'=>'email']; $userSort=$request->query('sort','latest'); $users=User::with(['role','level'])->when($request->filled('q'),fn($query)=>$query->where(fn($q)=>$q->where('name','like','%'.$request->q.'%')->orWhere('email','like','%'.$request->q.'%')))->when($request->filled('role'),fn($query)=>$query->where('role_id',$request->role))->when($request->filled('kyc'),fn($query)=>$query->where('kyc_status',$request->kyc))->when($request->filled('level'),fn($query)=>$query->where('level_id',$request->level))->orderBy($userSorts[$userSort] ?? 'created_at',in_array($userSort,['name','email'],true) ? 'asc' : ($userSort==='oldest' ? 'asc' : 'desc'))->paginate(10)->withQueryString(); return view('users.index', ['tab'=>$tab,'users'=>$users,'roles'=>$roles,'roleOptions'=>$roleOptions,'levelOptions'=>$levelOptions]); }
    public function create() { return view('users.create', ['roles' => Role::orderBy('name')->get(), 'levels' => Level::orderBy('sort_order')->get()]); }
    public function store(Request $request) { $data = $request->validate(['name'=>'required|string|max:120','email'=>'required|email|unique:users,email','password'=>'required|string|min:8','role_id'=>'required|exists:roles,id','level_id'=>'required|exists:levels,id','kyc_status'=>'required|in:PENDING,VERIFIED,REJECTED']); $user=User::create($data); ActivityLog::create(['user_id'=>auth()->id(),'action'=>'USER_CREATED','description'=>"Membuat pengguna {$user->name}",'entity_type'=>'User','entity_id'=>$user->id]); return redirect()->route('users.index')->with('success','Pengguna berhasil dibuat.'); }
    public function edit(User $user) { return view('users.edit', ['user'=>$user,'roles'=>Role::orderBy('name')->get(), 'levels' => Level::orderBy('sort_order')->get()]); }
    public function update(Request $request, User $user) { $data = $request->validate(['name'=>'required|string|max:120','email'=>'required|email|unique:users,email,'.$user->id,'password'=>'nullable|string|min:8','role_id'=>'required|exists:roles,id','level_id'=>'required|exists:levels,id','kyc_status'=>'required|in:PENDING,VERIFIED,REJECTED']); if (blank($data['password'] ?? null)) unset($data['password']); $user->update($data); ActivityLog::create(['user_id'=>auth()->id(),'action'=>'USER_UPDATED','description'=>"Memperbarui pengguna {$user->name}",'entity_type'=>'User','entity_id'=>$user->id]); return redirect()->route('users.index')->with('success','Pengguna berhasil diperbarui.'); }
    public function destroy(User $user) { $name=$user->name; $id=$user->id; $user->delete(); ActivityLog::create(['user_id'=>auth()->id(),'action'=>'USER_DELETED','description'=>"Menghapus pengguna {$name}",'entity_type'=>'User','entity_id'=>$id]); return redirect()->route('users.index')->with('success','Pengguna berhasil dihapus.'); }
    public function resetPassword(Request $request, User $user) { $data=$request->validate(['password'=>'required|string|min:8|confirmed']); $user->update(['password'=>$data['password']]); ActivityLog::create(['user_id'=>auth()->id(),'action'=>'PASSWORD_RESET','description'=>"Mereset password pengguna {$user->name}",'entity_type'=>'User','entity_id'=>$user->id]); return redirect()->route('users.index')->with('success','Password pengguna berhasil direset.'); }
    public function storeRole(Request $request) { $data=$request->validate(['name'=>'required|string|max:40|unique:roles,name','description'=>'nullable|string|max:500']); $role=Role::create(['name'=>strtoupper($data['name']),'description'=>$data['description']??null]); ActivityLog::create(['user_id'=>auth()->id(),'action'=>'ROLE_CREATED','description'=>"Membuat peran {$role->name}",'entity_type'=>'Role','entity_id'=>$role->id]); return redirect('/users?tab=roles')->with('success','Peran berhasil dibuat.'); }
    public function updateRole(Request $request, Role $role) { $data=$request->validate(['name'=>'required|string|max:40|unique:roles,name,'.$role->id,'description'=>'nullable|string|max:500']); $role->update(['name'=>strtoupper($data['name']),'description'=>$data['description']??null]); ActivityLog::create(['user_id'=>auth()->id(),'action'=>'ROLE_UPDATED','description'=>"Memperbarui peran {$role->name}",'entity_type'=>'Role','entity_id'=>$role->id]); return redirect('/users?tab=roles')->with('success','Peran berhasil diperbarui.'); }
    public function destroyRole(Role $role) { $name=$role->name; $id=$role->id; $role->users()->update(['role_id'=>null]); $role->delete(); ActivityLog::create(['user_id'=>auth()->id(),'action'=>'ROLE_DELETED','description'=>"Menghapus peran {$name}",'entity_type'=>'Role','entity_id'=>$id]); return redirect('/users?tab=roles')->with('success','Peran berhasil dihapus.'); }
}
