<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\{EWallet,FeeSetting,Order,Trip,WalletTransaction}; use App\Services\ShippingCalculator; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class OrderController extends Controller
{
 public function store(Request $r,ShippingCalculator $shipping){$d=$r->validate(['type'=>'nullable|in:ANTAR_WARGA,INTERNATIONAL_PO','trip_reference'=>'required_if:type,INTERNATIONAL_PO|string|max:120','origin_zone'=>'required|string|max:80','destination_zone'=>'required|string|max:80','weight_lbs'=>'required|numeric|min:0.1','pickup_address'=>'required_if:type,ANTAR_WARGA|string','delivery_address'=>'required|string','item_description'=>'required|string','item_count'=>'nullable|integer|min:1','item_cost'=>'nullable|integer|min:0','dp_required'=>'nullable|boolean','dp_amount'=>'nullable|integer|min:0']);$quote=$shipping->quote($d['origin_zone'],$d['destination_zone'],(float)$d['weight_lbs']);$type=$d['type']??'ANTAR_WARGA';$itemCount=$d['item_count']??1;$order=Order::create(array_merge($d,$quote,['customer_id'=>$r->user()->id,'status'=>$type==='INTERNATIONAL_PO'?'PO_PENDING':'SEARCHING_COURIER','type'=>$type,'commission'=>0,'courier_fee'=>FeeSetting::value('courier_fee',1000)*$itemCount]));return response()->json(['order'=>$order,'courier_fee_per_item'=>FeeSetting::value('courier_fee',1000),'shipping_quote'=>$quote],201);}
 public function shippingQuote(Request $r,ShippingCalculator $shipping){$d=$r->validate(['origin_zone'=>'required|string','destination_zone'=>'required|string','weight_lbs'=>'required|numeric|min:0.1']);return response()->json($shipping->quote($d['origin_zone'],$d['destination_zone'],(float)$d['weight_lbs']));}
 public function claim(Request $r,Order $order){$claimed=DB::transaction(function()use($r,$order){$locked=Order::whereKey($order->id)->lockForUpdate()->first();if(!$locked||$locked->status!=='SEARCHING_COURIER')return null;$locked->update(['courier_id'=>$r->user()->id,'status'=>'ACCEPTED']);return $locked->fresh();});return $claimed?response()->json(['order'=>$claimed]):response()->json(['message'=>'Order sudah diambil kurir lain'],409);}
 public function setDp(Request $r,Order $order){$this->ensureOwner($r,$order);$d=$r->validate(['dp_required'=>'required|boolean','dp_amount'=>'nullable|integer|min:0']);if($d['dp_required']&&empty($d['dp_amount']))return response()->json(['message'=>'Nominal DP wajib diisi'],422);$order->update(['dp_required'=>$d['dp_required'],'dp_amount'=>$d['dp_amount']??0]);return response()->json(['order'=>$order->fresh()]);}
 public function uploadInvoice(Request $r,Order $order){$this->ensureOwner($r,$order);$r->validate(['invoice'=>'required|image|max:5120']);$path=$r->file('invoice')->store('invoices','public');$order->update(['invoice_photo'=>$path,'invoice_details'=>['ocr_status'=>'MOCK_PROCESSED','merchant'=>'Toko Mock Titip Kilat','total'=>(int)$order->item_cost,'items'=>[$order->item_description]],'status'=>'INVOICE_UPLOADED']);return response()->json(['order'=>$order->fresh(),'ocr'=>$order->invoice_details]);}
 public function updateStatus(Request $r,Order $order){$this->ensureOwner($r,$order);$d=$r->validate(['status'=>'required|in=PURCHASED,OUT_FOR_DELIVERY,DELIVERED']);$order->update(['status'=>$d['status']]);return response()->json(['order'=>$order->fresh()]);}
 public function acceptPo(Request $r,Order $order){$d=$r->validate(['trip_reference'=>'required|string|exists:trips,code']);$trip=Trip::where('code',$d['trip_reference'])->where('traveler_id',$r->user()->id)->first();if($order->type!=='INTERNATIONAL_PO'||$order->status!=='PO_PENDING'||!$trip)return response()->json(['message'=>'PO atau jadwal trip tidak valid'],422);$order->update(['traveler_id'=>$r->user()->id,'status'=>'PO_ACCEPTED']);return response()->json(['order'=>$order->fresh(),'trip'=>$trip]);}
 public function uploadPurchase(Request $r,Order $order){$this->ensureTraveler($r,$order);$r->validate(['purchase_photo'=>'required|image|max:5120']);$path=$r->file('purchase_photo')->store('purchases','public');$order->update(['purchase_photo'=>$path,'status'=>'PURCHASED']);return response()->json(['order'=>$order->fresh()]);}
 public function shipInternational(Request $r,Order $order){$this->ensureTraveler($r,$order);if($order->status!=='PURCHASED')return response()->json(['message'=>'Foto pembelian wajib diunggah sebelum pengiriman'],422);$order->update(['status'=>'SHIPPED']);return response()->json(['order'=>$order->fresh()]);}
 public function complete(Request $r,Order $order){abort_unless((int)$order->customer_id===(int)$r->user()->id,403,'Hanya pemilik order yang dapat menyelesaikan transaksi');if(!in_array($order->status,['DELIVERED','SHIPPED'],true))return response()->json(['message'=>'Order belum siap diselesaikan'],422);$result=DB::transaction(function()use($r,$order){$locked=Order::whereKey($order->id)->lockForUpdate()->first();if($locked->status==='COMPLETED')return $locked;$fee=FeeSetting::value('app_commission',1000);$wallet=EWallet::where('user_id',$r->user()->id)->lockForUpdate()->first();if(!$wallet||$wallet->balance<$fee)return null;$wallet->decrement('balance',$fee);WalletTransaction::create(['e_wallet_id'=>$wallet->id,'type'=>'PLATFORM_FEE','debit'=>$fee,'credit'=>0,'amount'=>$fee,'fee'=>0,'description'=>'Biaya platform transaksi selesai','reference'=>'ORDER-'.$locked->id]);$locked->update(['commission'=>$fee,'status'=>'COMPLETED']);return $locked->fresh();});return $result?response()->json(['order'=>$result,'platform_fee'=>$result->commission]):response()->json(['message'=>'Saldo tidak cukup untuk biaya platform Rp1.000'],422);}
 public function show(Order $order){return response()->json($order->load('customer','courier','traveler'));}
 private function ensureOwner(Request $r,Order $order):void{abort_unless((int)$order->courier_id===(int)$r->user()->id,403,'Order bukan milik kurir ini');}
 private function ensureTraveler(Request $r,Order $order):void{abort_unless((int)$order->traveler_id===(int)$r->user()->id,403,'PO bukan milik traveler ini');}
}
