@extends('layouts.app')
@section('content')
<style>
 .orders-hero{display:flex;align-items:end;justify-content:space-between;gap:20px;padding:32px 38px;margin-bottom:18px;border-radius:26px;background:linear-gradient(120deg,#1d4ed8,#6366f1);color:#fff;box-shadow:0 20px 48px rgba(37,99,235,.18)}.orders-hero h1{color:#fff;font-size:clamp(32px,5vw,56px);letter-spacing:-.06em}.orders-hero p{margin-top:7px;color:rgba(255,255,255,.75);font-size:14px}.order-filters{display:flex;gap:8px;margin-bottom:16px}.order-empty{min-height:320px;display:grid;place-items:center}@media(max-width:620px){.orders-hero{display:block;padding:28px 24px}.orders-hero .btn{margin-top:20px}.order-filters{overflow:auto}}
</style>
<div class="section-header" style="margin-bottom:26px"><div><div style="font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#2563eb"><i class="bi bi-receipt"></i> Ruang kerja / Pesanan</div><h1 style="font-size:clamp(32px,5vw,56px);letter-spacing:-.06em;margin-top:8px">Jaga setiap pengiriman tetap berjalan.</h1><p style="color:var(--muted);font-size:14px;margin-top:8px">Pantau permintaan lokal dan pre-pesanan internasional dalam satu tempat.</p></div>@if(auth()->user()?->role?->name !== 'SUPER_ADMIN')<a href="{{ url('/orders/create') }}" class="btn btn-primary" data-order-modal><i class="bi bi-plus-lg"></i> Pesanan baru</a>@endif</div>
<form method="GET" class="card order-filters" style="display:flex;flex-wrap:wrap;align-items:end;margin-bottom:16px"><label style="flex:2;min-width:220px;color:var(--slate);font-size:11px;font-weight:700">Cari pesanan<input class="form-input" name="q" value="{{ request('q') }}" placeholder="Barang, rute, atau pelanggan"></label><label style="flex:1;min-width:145px;color:var(--slate);font-size:11px;font-weight:700">Kategori status<select class="form-input" name="status"><option value="">Semua status</option>@foreach(['SEARCHING_COURIER','COURIER_ASSIGNED','PICKED_UP','IN_TRANSIT','DELIVERED','COMPLETED','PO_PENDING','PO_ACCEPTED'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select></label><label style="flex:1;min-width:145px;color:var(--slate);font-size:11px;font-weight:700">Jenis pesanan<select class="form-input" name="type"><option value="">Semua jenis</option><option value="ANTAR_WARGA" @selected(request('type')==='ANTAR_WARGA')>Antar Warga</option><option value="INTERNATIONAL_PO" @selected(request('type')==='INTERNATIONAL_PO')>Internasional</option></select></label><label style="flex:1;min-width:145px;color:var(--slate);font-size:11px;font-weight:700">Urutkan<select class="form-input" name="sort"><option value="latest" @selected(request('sort','latest')==='latest')>Terbaru</option><option value="oldest" @selected(request('sort')==='oldest')>Terlama</option><option value="cost_high" @selected(request('sort')==='cost_high')>Biaya tertinggi</option><option value="cost_low" @selected(request('sort')==='cost_low')>Biaya terendah</option></select></label><button class="btn btn-primary btn-sm" type="submit"><i class="bi bi-search"></i> Terapkan</button><a class="btn btn-outline btn-sm" href="{{ url('/orders') }}">Reset</a></form>
@if($orders->isEmpty())<div class="card order-empty"><div class="empty"><div class="empty-icon"><i class="bi bi-receipt"></i></div><div class="empty-title">Belum ada pesanan</div><p style="margin-bottom:16px">Pesanan kamu akan muncul di sini setelah dibuat.</p>@if(auth()->user()?->role?->name !== 'SUPER_ADMIN')<a href="{{ url('/orders/create') }}" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Buat pesanan pertama</a>@endif</div></div>@else
<div class="card table-wrap"><table class="users-table"><thead><tr><th>Barang</th><th>Pelanggan</th><th>Rute</th><th>Status</th><th>Biaya</th></tr></thead><tbody>@foreach($orders as $order)<tr><td><strong>{{ $order->item_description }}</strong><div class="user-email">{{ $order->item_count }} item · {{ $order->weight_lbs }} lbs</div></td><td>{{ $order->customer?->name ?? '—' }}</td><td>{{ $order->origin_zone }} → {{ $order->destination_zone }}</td><td><span class="badge {{ $order->status === 'COMPLETED' ? 'badge-green' : 'badge-orange' }}">{{ $order->status }}</span></td><td>Rp {{ number_format($order->shipping_cost,0,',','.') }}</td></tr>@endforeach</tbody></table></div><div class="pagination-wrap">{{ $orders->links() }}</div>@endif
@endsection
