@extends('layouts.app')
@section('content')
<style>
.orders-hero{display:flex;justify-content:space-between;gap:24px;padding:30px 34px;margin-bottom:18px;border-radius:26px;background:linear-gradient(120deg,#1d4ed8,#6366f1);color:#fff}.orders-hero h1{color:#fff;font-size:clamp(28px,4vw,46px)}.orders-hero p{margin-top:7px;color:#dbeafe;font-size:14px}.orders-hero .btn{background:#fff;color:#2563eb}.order-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:14px}.order-card{padding:20px;border:1px solid var(--border);border-radius:20px;background:var(--surface)}.order-card h3{font-size:18px;margin:10px 0 5px}.order-meta{display:grid;gap:9px;margin:18px 0;color:var(--slate);font-size:12px}.order-meta div{display:flex;gap:9px;align-items:flex-start}.order-meta i{color:#2563eb}.order-route{display:flex;gap:9px;padding:11px 12px;border-radius:12px;background:#eff6ff;color:#1e40af;font-size:12px;font-weight:800}.order-card .btn{width:100%;justify-content:center}.order-filters{display:flex;flex-wrap:wrap;gap:10px;align-items:end;margin-bottom:18px}.order-filters label{flex:1;min-width:150px;color:var(--slate);font-size:11px;font-weight:700}.order-filters label:first-child{flex:2;min-width:220px}.courier-hint,.live-dispatch{margin-bottom:16px;padding:14px 17px;border:1px solid #bfdbfe;border-radius:16px;background:#eff6ff;color:#1e40af;font-size:13px}.live-dispatch{display:flex;justify-content:space-between;gap:16px;align-items:center;background:linear-gradient(120deg,#eff6ff,#f5f3ff)}.live-dispatch h2{font-size:18px;color:#172554}.live-dispatch p{margin-top:4px;color:#526581;font-size:12px}.live-status{display:flex;align-items:center;gap:9px;color:#526581;font-size:12px;font-weight:700}.live-dot{width:9px;height:9px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 5px #dcfce7}.status-title{margin:18px 0 8px;color:var(--slate);font-size:11px;font-weight:800;text-transform:uppercase}.status-track{display:flex;margin:0 0 18px}.status-step{position:relative;flex:1;color:#94a3b8;font-size:10px;text-align:center}.status-step:not(:last-child)::after{content:'';position:absolute;top:8px;left:calc(50% + 8px);width:calc(100% - 16px);height:2px;background:#e2e8f0}.status-step.done{color:#2563eb;font-weight:800}.status-step.done:not(:last-child)::after{background:#93c5fd}.status-dot{position:relative;z-index:1;display:block;width:16px;height:16px;margin:0 auto 5px;border:3px solid #e2e8f0;border-radius:50%;background:var(--surface)}.status-step.done .status-dot{border-color:#2563eb;background:#2563eb}.status-step.current .status-dot{box-shadow:0 0 0 4px #dbeafe}.next-status{margin-top:12px}@media(max-width:620px){.orders-hero{display:block;padding:26px 22px}.orders-hero .btn{margin-top:18px}.order-grid{grid-template-columns:1fr}.live-dispatch{display:block}.live-status{margin-top:12px}.status-step{font-size:8px}}
</style>
@php($isCourier = $role === 'COURIER')
@php($statusSteps = [['key'=>'COURIER_ASSIGNED','label'=>'Diambil'],['key'=>'PICKED_UP','label'=>'Barang diambil'],['key'=>'PURCHASED','label'=>'Sudah dibeli'],['key'=>'OUT_FOR_DELIVERY','label'=>'Diantar'],['key'=>'DELIVERED','label'=>'Tiba'],['key'=>'COMPLETED','label'=>'Selesai']])
<div class="orders-hero"><div><div style="font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;opacity:.8">{{ $isCourier ? 'Kurir / Pesanan aktif' : 'Jastip / Pesanan saya' }}</div><h1>{{ $isCourier ? 'Antar pesanan dengan jelas.' : 'Pantau titipanmu.' }}</h1><p>{{ $isCourier ? 'Perbarui status setiap langkah agar pelanggan selalu tahu progresnya.' : 'Lihat progres belanja dan pengantaran secara langsung.' }}</p></div>
@if($role === 'USER')
<a href="{{ route('orders.create') }}" class="btn"><i class="bi bi-plus-lg"></i> Buat permintaan</a>
@endif
</div>
@if($isCourier)
<div class="courier-hint"><i class="bi bi-info-circle"></i> Kamu hanya dapat mengerjakan satu pesanan aktif. Selesaikan sampai diantar sebelum mengambil pesanan lain.</div>
<div class="live-dispatch"><div><div style="font-size:10px;letter-spacing:.14em;font-weight:900;color:#2563eb">LIVE DISPATCH</div><h2>{{ $courierBusy ? 'Selesaikan pesanan aktifmu.' : 'Menunggu pesanan baru.' }}</h2><p>{{ $courierBusy ? 'Pesanan lain dikunci sampai pesanan ini selesai.' : 'Pilih lokasi aktif untuk menerima permintaan yang sesuai.' }}</p></div><div class="live-status"><span class="live-dot"></span><span id="live-status">{{ $courierBusy ? '1 pesanan sedang dikerjakan' : 'Sedang memantau' }}</span></div></div>
@endif
<form method="GET" class="card order-filters"><label>Cari barang atau kota<input class="form-input" name="q" value="{{ request('q') }}" placeholder="Contoh: skincare, Jakarta"></label>
@if($isCourier)<label>Lokasi saya<select class="form-input" name="zone"><option value="">Semua lokasi</option>@foreach($zones as $zone)<option value="{{ $zone }}" @selected(request('zone') === $zone)>{{ $zone }}</option>@endforeach</select></label>@endif
<label>Status<select class="form-input" name="status"><option value="">Semua status</option>@foreach(['SEARCHING_COURIER','COURIER_ASSIGNED','PICKED_UP','PURCHASED','OUT_FOR_DELIVERY','DELIVERED','COMPLETED'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str_replace('_',' ',$status) }}</option>@endforeach</select></label><button class="btn btn-primary btn-sm" type="submit">Cari</button><a class="btn btn-outline btn-sm" href="{{ route('orders.index') }}">Reset</a></form>
@if($orders->isEmpty())
<div class="card order-empty"><div class="empty"><div class="empty-icon"><i class="bi bi-bag-x"></i></div><div class="empty-title">Belum ada permintaan</div><p style="margin-bottom:16px">{{ $isCourier ? 'Belum ada pesanan di lokasi ini.' : 'Buat permintaan pertama agar kurir bisa membantu membelinya.' }}</p>
@if($role === 'USER')<a href="{{ route('orders.create') }}" class="btn btn-primary">Buat permintaan</a>@endif
</div></div>
@else
<div class="order-grid">
@foreach($orders as $order)
@php($currentIndex = collect($statusSteps)->search(fn($step) => $step['key'] === $order->status))
<article class="order-card" data-order-id="{{ $order->id }}"><div style="display:flex;justify-content:space-between;align-items:center"><span class="badge {{ $order->status === 'SEARCHING_COURIER' ? 'badge-orange' : ($order->status === 'COMPLETED' ? 'badge-green' : 'badge-blue') }}">{{ str_replace('_',' ',$order->status) }}</span><small style="color:var(--muted)">#{{ $order->id }}</small></div><h3>{{ $order->item_description }}</h3>
@if($order->item_items)<div style="display:grid;gap:5px;margin-top:9px;color:var(--slate);font-size:12px">@foreach($order->item_items as $item)<div><i class="bi bi-check2" style="color:#2563eb"></i> {{ $item['quantity'] }}× {{ $item['name'] }}@if(!empty($item['notes'])) <span style="color:var(--muted)">— {{ $item['notes'] }}</span>@endif</div>@endforeach</div>@endif
<div style="color:var(--muted);font-size:12px;margin-top:9px">{{ $order->item_count }} total item · Budget Rp {{ number_format($order->item_cost,0,',','.') }}</div><div class="order-meta"><div class="order-route"><i class="bi bi-shop"></i>{{ $order->origin_zone }} <i class="bi bi-arrow-right"></i> {{ $order->destination_zone }}</div><div><i class="bi bi-geo-alt"></i><span><strong>Belanja:</strong> {{ $order->pickup_address }}</span></div><div><i class="bi bi-house-check"></i><span><strong>Kirim:</strong> {{ $order->delivery_address }}</span></div><div><i class="bi bi-person"></i><span>{{ $order->customer?->name ?? 'Pelanggan' }}@if($order->courier) · Kurir: {{ $order->courier->name }}@endif</span></div></div>
@if($order->status !== 'SEARCHING_COURIER')<div class="status-title">Progress pesanan</div><div class="status-track">@foreach($statusSteps as $index=>$step)<div class="status-step {{ $currentIndex !== false && $index <= $currentIndex ? 'done' : '' }} {{ $step['key'] === $order->status ? 'current' : '' }}"><span class="status-dot"></span>{{ $step['label'] }}</div>@endforeach</div>@endif
@if($isCourier && in_array($order->status,['COURIER_ASSIGNED','ACCEPTED','PICKED_UP','PURCHASED','OUT_FOR_DELIVERY','IN_TRANSIT'],true))
<form method="POST" action="{{ route('orders.status',$order) }}" class="next-status">@csrf<button class="btn btn-primary" type="submit"><i class="bi bi-arrow-right-circle"></i> {{ ['COURIER_ASSIGNED'=>'Saya sudah ambil barang','ACCEPTED'=>'Saya sudah ambil barang','PICKED_UP'=>'Barang sudah dibeli','PURCHASED'=>'Mulai antar ke pelanggan','OUT_FOR_DELIVERY'=>'Pesanan sudah sampai','IN_TRANSIT'=>'Pesanan sudah sampai'][$order->status] }}</button></form>
@endif
@if($role === 'USER' && (int)$order->customer_id === (int)auth()->id() && $order->status === 'DELIVERED')
<form method="POST" action="{{ route('orders.complete',$order) }}" class="next-status">@csrf<button class="btn btn-primary" type="submit"><i class="bi bi-check-circle"></i> Konfirmasi pesanan selesai</button></form>
@endif
@if($isCourier && $order->status === 'SEARCHING_COURIER')
<form method="POST" action="{{ route('orders.claim',$order) }}">@csrf<button class="btn btn-primary" type="submit"><i class="bi bi-lightning-charge"></i> Ambil pesanan ini</button></form>
@endif
</article>
@endforeach
</div><div class="pagination-wrap">{{ $orders->links() }}</div>
@endif
@if($isCourier)
<script>(()=>{const status=document.getElementById('live-status');const zone=@json(request('zone',''));let known=new Set([...document.querySelectorAll('[data-order-id]')].map(card=>card.dataset.orderId));const check=async()=>{try{const response=await fetch(`{{ route('orders.feed') }}?zone=${encodeURIComponent(zone)}`,{headers:{Accept:'application/json'}});if(!response.ok)return;const data=await response.json();if(data.busy){if(status)status.textContent='Pesanan aktif sedang dikerjakan';return;}const fresh=data.orders.filter(order=>!known.has(String(order.id)));if(fresh.length){window.showToast?.(`Pesanan baru: ${fresh[0].item}`,'info');setTimeout(()=>window.location.reload(),900);}known=new Set(data.orders.map(order=>String(order.id)));if(status)status.textContent=`Aktif · ${data.count} tersedia`;}catch(error){if(status)status.textContent='Menunggu koneksi…';}};setInterval(check,8000);})();</script>
@endif
@endsection
